# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ src ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run-script start
      
#     - name: Install SSH Key
#       uses: shimataro/ssh-key-action@v2.0.3
#       with:
#         # SSH private key
#         key: ${{ secrets.SFTP_PRIVATE_KEY }}
#         # SSH key file name (default: id_rsa)
#         name: jbossorg_rsa # optional, default is id_rsa
#         # public keys of SSH servers
#         known_hosts: ${{ secrets.SFTP_PUBLIC_KEY }} # default is 

    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        # username
        username: ${{ secrets.SFTP_USER }}
        # your sftp server
        server: ${{ secrets.SFTP_SERVER }}
        # your sftp server port, default to 22
        port: 22 # default is 22
        # you can copy private_key from your *.pem file, keep format
        ssh_private_key: ${{ secrets.SFTP_PRIVATE_KEY }}
        # will put all file under this path
        local_path: './gh-pages/*' # default is ./*
        # files will copy to under remote_path
        remote_path: ${{ secrets.SFTP_PATH }} # default is /
        # sftp args
        #args: # optional  
        
    - name: GitHub Pages Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: master
        build_dir: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
